### ISSUE TITLE
Installation Problems (environment_dev.yml not found error...)

### ISSUE THREAD

**Issue by Hadi-Borjkhani** [ibs-lab/cedalion#69]
Hi,

Please make clear in the installation instruction that we need to clone the cedalion first. 
because I faced environment_dev.yml not found error:

```
conda env create -n cedalion -f environment_dev.yml
```

After I cloned the Cedalion. I did these steps:

```
cd C:\Users\borjkha\Documents\Hadi-PhD\GitLab\Cedalion\cedalion-main    # the cloned path in my PC
conda env create -n cedalion -f environment_dev.yml
```

But still I have faced error in excuting this command:
- pip install -e .

```
(cedalion) C:\Users\borjkha\Documents\Hadi-PhD\GitLab\Cedalion\cedalion-main>pip install -e .
Obtaining file:///C:/Users/borjkha/Documents/Hadi-PhD/GitLab/Cedalion/cedalion-main
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      Traceback (most recent call last):
        File "C:\Users\lokalAdmin\.conda\envs\cedalion\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\lokalAdmin\.conda\envs\cedalion\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\lokalAdmin\.conda\envs\cedalion\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\lokalAdmin\AppData\Local\Temp\pip-build-env-ezhr9qqe\overlay\Lib\site-packages\setuptools\build_meta.py", line 483, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\lokalAdmin\AppData\Local\Temp\pip-build-env-ezhr9qqe\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\lokalAdmin\AppData\Local\Temp\pip-build-env-ezhr9qqe\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "C:\Users\lokalAdmin\AppData\Local\Temp\pip-build-env-ezhr9qqe\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "C:\Users\lokalAdmin\AppData\Local\Temp\pip-build-env-ezhr9qqe\overlay\Lib\site-packages\setuptools\__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\lokalAdmin\AppData\Local\Temp\pip-build-env-ezhr9qqe\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 145, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "C:\Users\lokalAdmin\AppData\Local\Temp\pip-build-env-ezhr9qqe\overlay\Lib\site-packages\setuptools\dist.py", line 319, in __init__
          _Distribution.__init__(self, dist_attrs)
        File "C:\Users\lokalAdmin\AppData\Local\Temp\pip-build-env-ezhr9qqe\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 279, in __init__
          self.finalize_options()
        File "C:\Users\lokalAdmin\AppData\Local\Temp\pip-build-env-ezhr9qqe\overlay\Lib\site-packages\setuptools\dist.py", line 677, in finalize_options
          ep(self)
        File "C:\Users\lokalAdmin\AppData\Local\Temp\pip-build-env-ezhr9qqe\overlay\Lib\site-packages\setuptools_scm\_integration\setuptools.py", line 123, in infer_version
          _assign_version(dist, config)
        File "C:\Users\lokalAdmin\AppData\Local\Temp\pip-build-env-ezhr9qqe\overlay\Lib\site-packages\setuptools_scm\_integration\setuptools.py", line 58, in _assign_version
          _version_missing(config)
        File "C:\Users\lokalAdmin\AppData\Local\Temp\pip-build-env-ezhr9qqe\overlay\Lib\site-packages\setuptools_scm\_get_version_impl.py", line 117, in _version_missing
          raise LookupError(
      LookupError: setuptools-scm was unable to detect version for C:\Users\borjkha\Documents\Hadi-PhD\GitLab\Cedalion\cedalion-main.

      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by Hadi-Borjkhani** [comment]
Sorry for the issue report I could fix the problem.

```
(cedalion) C:\Users\borjkha\Documents\Hadi-PhD\GitLab\Cedalion\cedalion>pip install -e .
Obtaining file:///C:/Users/borjkha/Documents/Hadi-PhD/GitLab/Cedalion/cedalion
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Building wheels for collected packages: cedalion
  Building editable for cedalion (pyproject.toml) ... done
  Created wheel for cedalion: filename=cedalion-0.1.dev453+gd965389-0.editable-py3-none-any.whl size=3622 sha256=041d9a616b88c527c18cb3646f4d3de7a75ba17b1e50cbb68b8fde9ad4a847f4
  Stored in directory: C:\Users\lokalAdmin\AppData\Local\Temp\pip-ephem-wheel-cache-chxlbz7_\wheels\30\25\5b\7bc8230194781847b009db3b1ec73cb4f9e4059891bc288405
Successfully built cedalion
Installing collected packages: cedalion
Successfully installed cedalion-0.1.dev453+gd965389
```

For those who may face similar issue.

- install git
- open gitbash in the folder that you want to save the cedalion:
```
git clone https://github.com/ibs-lab/cedalion.git
```
Now open your conda prompt. In the conda prompt 
```
cd C:\Users....\ Cedalion # the address that you have cedalion cloned

```
[follow the instruction in the installation documation of cedalion](https://doc.ibs.tu-berlin.de/cedalion/doc/dev/getting_started/installation.html#environments.md)

**Comment by aykuteken** [comment]
@Hadi-Borjkhani I'm getting such an error when I wanted to use cedalion over spyder.

"Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem."

Anyone experienced such an error before?
